# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoSUIT.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(694, 700)
        Dialog.setMaximumSize(QtCore.QSize(694, 700))
        font = QtGui.QFont()
        font.setPointSize(6)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.page.setObjectName("page")
        self.SetBtnHelp = QtWidgets.QPushButton(self.page)
        self.SetBtnHelp.setGeometry(QtCore.QRect(581, 250, 72, 24))
        self.SetBtnHelp.setMaximumSize(QtCore.QSize(72, 24))
        self.SetBtnHelp.setObjectName("SetBtnHelp")
        self.SetBtnAbout = QtWidgets.QPushButton(self.page)
        self.SetBtnAbout.setGeometry(QtCore.QRect(581, 280, 72, 24))
        self.SetBtnAbout.setMaximumSize(QtCore.QSize(72, 24))
        self.SetBtnAbout.setObjectName("SetBtnAbout")
        self.SetBtnBox = QtWidgets.QDialogButtonBox(self.page)
        self.SetBtnBox.setGeometry(QtCore.QRect(581, 190, 71, 56))
        self.SetBtnBox.setMaximumSize(QtCore.QSize(71, 114))
        self.SetBtnBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SetBtnBox.setOrientation(QtCore.Qt.Vertical)
        self.SetBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.SetBtnBox.setCenterButtons(True)
        self.SetBtnBox.setObjectName("SetBtnBox")
        self.BaseLayerLbl = QtWidgets.QLabel(self.page)
        self.BaseLayerLbl.setGeometry(QtCore.QRect(80, 0, 551, 20))
        self.BaseLayerLbl.setObjectName("BaseLayerLbl")
        self.OutlEdt = QtWidgets.QLineEdit(self.page)
        self.OutlEdt.setGeometry(QtCore.QRect(80, 30, 551, 20))
        self.OutlEdt.setObjectName("OutlEdt")
        self.RetriveFileTBtn = QtWidgets.QToolButton(self.page)
        self.RetriveFileTBtn.setGeometry(QtCore.QRect(640, 30, 25, 21))
        self.RetriveFileTBtn.setObjectName("RetriveFileTBtn")
        self.listAllFields = QtWidgets.QListWidget(self.page)
        self.listAllFields.setGeometry(QtCore.QRect(10, 80, 211, 381))
        self.listAllFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listAllFields.setObjectName("listAllFields")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(230, 60, 331, 101))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.addLayerBtnBUILT = QtWidgets.QPushButton(self.groupBox)
        self.addLayerBtnBUILT.setGeometry(QtCore.QRect(20, 30, 51, 23))
        self.addLayerBtnBUILT.setObjectName("addLayerBtnBUILT")
        self.listBuiltFields = QtWidgets.QListWidget(self.groupBox)
        self.listBuiltFields.setGeometry(QtCore.QRect(90, 30, 231, 61))
        self.listBuiltFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listBuiltFields.setObjectName("listBuiltFields")
        self.removeLayerBtnBUILT = QtWidgets.QPushButton(self.groupBox)
        self.removeLayerBtnBUILT.setGeometry(QtCore.QRect(20, 50, 51, 23))
        self.removeLayerBtnBUILT.setObjectName("removeLayerBtnBUILT")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 160, 331, 101))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.removeLayerBtnBIO = QtWidgets.QPushButton(self.groupBox_2)
        self.removeLayerBtnBIO.setGeometry(QtCore.QRect(20, 50, 51, 23))
        self.removeLayerBtnBIO.setObjectName("removeLayerBtnBIO")
        self.listBioFields = QtWidgets.QListWidget(self.groupBox_2)
        self.listBioFields.setGeometry(QtCore.QRect(90, 30, 231, 61))
        self.listBioFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listBioFields.setObjectName("listBioFields")
        self.addLayerBtnBIO = QtWidgets.QPushButton(self.groupBox_2)
        self.addLayerBtnBIO.setGeometry(QtCore.QRect(20, 30, 51, 23))
        self.addLayerBtnBIO.setObjectName("addLayerBtnBIO")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 260, 331, 101))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.addLayerBtnMOB = QtWidgets.QPushButton(self.groupBox_4)
        self.addLayerBtnMOB.setGeometry(QtCore.QRect(20, 30, 51, 23))
        self.addLayerBtnMOB.setObjectName("addLayerBtnMOB")
        self.removeLayerBtnMOB = QtWidgets.QPushButton(self.groupBox_4)
        self.removeLayerBtnMOB.setGeometry(QtCore.QRect(20, 50, 51, 23))
        self.removeLayerBtnMOB.setObjectName("removeLayerBtnMOB")
        self.listMobFields = QtWidgets.QListWidget(self.groupBox_4)
        self.listMobFields.setGeometry(QtCore.QRect(90, 30, 231, 61))
        self.listMobFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listMobFields.setObjectName("listMobFields")
        self.EcoFieldsLbl_2 = QtWidgets.QLabel(self.page)
        self.EcoFieldsLbl_2.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.EcoFieldsLbl_2.setObjectName("EcoFieldsLbl_2")
        self.EcoFieldsLbl_3 = QtWidgets.QLabel(self.page)
        self.EcoFieldsLbl_3.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.EcoFieldsLbl_3.setObjectName("EcoFieldsLbl_3")
        self.LblLogo = QtWidgets.QLabel(self.page)
        self.LblLogo.setGeometry(QtCore.QRect(580, 90, 81, 71))
        self.LblLogo.setText("")
        self.LblLogo.setScaledContents(True)
        self.LblLogo.setObjectName("LblLogo")
        self.LoadProgressBar = QtWidgets.QProgressBar(self.page)
        self.LoadProgressBar.setGeometry(QtCore.QRect(610, 320, 21, 131))
        self.LoadProgressBar.setProperty("value", 0)
        self.LoadProgressBar.setOrientation(QtCore.Qt.Vertical)
        self.LoadProgressBar.setObjectName("LoadProgressBar")
        self.groupBox_12 = QtWidgets.QGroupBox(self.page)
        self.groupBox_12.setGeometry(QtCore.QRect(230, 360, 331, 101))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.addLayerBtnSocialSpatial = QtWidgets.QPushButton(self.groupBox_12)
        self.addLayerBtnSocialSpatial.setGeometry(QtCore.QRect(20, 30, 51, 23))
        self.addLayerBtnSocialSpatial.setObjectName("addLayerBtnSocialSpatial")
        self.removeLayerBtnSocialSpatial = QtWidgets.QPushButton(self.groupBox_12)
        self.removeLayerBtnSocialSpatial.setGeometry(QtCore.QRect(20, 50, 51, 23))
        self.removeLayerBtnSocialSpatial.setObjectName("removeLayerBtnSocialSpatial")
        self.listSocioFields = QtWidgets.QListWidget(self.groupBox_12)
        self.listSocioFields.setGeometry(QtCore.QRect(90, 30, 231, 61))
        self.listSocioFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listSocioFields.setObjectName("listSocioFields")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()
        self.SetBtnHelp.raise_()
        self.SetBtnAbout.raise_()
        self.SetBtnBox.raise_()
        self.BaseLayerLbl.raise_()
        self.OutlEdt.raise_()
        self.RetriveFileTBtn.raise_()
        self.listAllFields.raise_()
        self.EcoFieldsLbl_2.raise_()
        self.EcoFieldsLbl_3.raise_()
        self.LblLogo.raise_()
        self.LoadProgressBar.raise_()
        self.groupBox_12.raise_()
        self.toolBox.addItem(self.page, "")
        self.EnvironmentaleQTbox = QtWidgets.QWidget()
        self.EnvironmentaleQTbox.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.EnvironmentaleQTbox.setObjectName("EnvironmentaleQTbox")
        self.EnvLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(9, 0, 51, 16))
        self.EnvLbl.setObjectName("EnvLbl")
        self.BuiltMapNameLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.BuiltMapNameLbl.setGeometry(QtCore.QRect(69, 0, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.BuiltMapNameLbl.setFont(font)
        self.BuiltMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.BuiltMapNameLbl.setObjectName("BuiltMapNameLbl")
        self.line_2 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_2.setGeometry(QtCore.QRect(9, 10, 657, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_4.setGeometry(QtCore.QRect(10, 360, 660, 15))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.EnvironmentaleQTbox)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 30, 661, 331))
        self.groupBox_11.setObjectName("groupBox_11")
        self.BuiltGetWeightBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.BuiltGetWeightBtn.setGeometry(QtCore.QRect(550, 290, 104, 24))
        self.BuiltGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.BuiltGetWeightBtn.setObjectName("BuiltGetWeightBtn")
        self.BuiltWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_11)
        self.BuiltWeighTableWidget.setGeometry(QtCore.QRect(20, 31, 630, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BuiltWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.BuiltWeighTableWidget.setSizePolicy(sizePolicy)
        self.BuiltWeighTableWidget.setAcceptDrops(False)
        self.BuiltWeighTableWidget.setDragEnabled(True)
        self.BuiltWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.BuiltWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.BuiltWeighTableWidget.setRowCount(0)
        self.BuiltWeighTableWidget.setObjectName("BuiltWeighTableWidget")
        self.BuiltWeighTableWidget.setColumnCount(0)
        self.BuiltWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.BuiltWeighTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.BuiltWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.BuiltWeighTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.BuiltWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.EnvProgressBar = QtWidgets.QProgressBar(self.groupBox_11)
        self.EnvProgressBar.setGeometry(QtCore.QRect(170, 290, 371, 25))
        self.EnvProgressBar.setProperty("value", 0)
        self.EnvProgressBar.setObjectName("EnvProgressBar")
        self.BuiltSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.BuiltSaveCfgBtn.setGeometry(QtCore.QRect(20, 290, 104, 24))
        self.BuiltSaveCfgBtn.setObjectName("BuiltSaveCfgBtn")
        self.groupBox_15 = QtWidgets.QGroupBox(self.EnvironmentaleQTbox)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 380, 651, 71))
        self.groupBox_15.setObjectName("groupBox_15")
        self.lblOutputA = QtWidgets.QLabel(self.groupBox_15)
        self.lblOutputA.setGeometry(QtCore.QRect(10, 30, 631, 16))
        self.lblOutputA.setObjectName("lblOutputA")
        self.toolBox.addItem(self.EnvironmentaleQTbox, "")
        self.EconomicsQTBox = QtWidgets.QWidget()
        self.EconomicsQTBox.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.EconomicsQTBox.setObjectName("EconomicsQTBox")
        self.EcoLbl = QtWidgets.QLabel(self.EconomicsQTBox)
        self.EcoLbl.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.EcoLbl.setObjectName("EcoLbl")
        self.BioMapNameLbl = QtWidgets.QLabel(self.EconomicsQTBox)
        self.BioMapNameLbl.setGeometry(QtCore.QRect(90, 0, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.BioMapNameLbl.setFont(font)
        self.BioMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.BioMapNameLbl.setObjectName("BioMapNameLbl")
        self.line_5 = QtWidgets.QFrame(self.EconomicsQTBox)
        self.line_5.setGeometry(QtCore.QRect(8, 10, 657, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.EconomicsQTBox)
        self.line_7.setGeometry(QtCore.QRect(10, 360, 660, 15))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.groupBox_10 = QtWidgets.QGroupBox(self.EconomicsQTBox)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 20, 661, 341))
        self.groupBox_10.setObjectName("groupBox_10")
        self.BioWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_10)
        self.BioWeighTableWidget.setGeometry(QtCore.QRect(20, 33, 630, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BioWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.BioWeighTableWidget.setSizePolicy(sizePolicy)
        self.BioWeighTableWidget.setDragEnabled(True)
        self.BioWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.BioWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.BioWeighTableWidget.setRowCount(0)
        self.BioWeighTableWidget.setObjectName("BioWeighTableWidget")
        self.BioWeighTableWidget.setColumnCount(0)
        self.BioWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.BioWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.BioWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.BioWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.BioSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_10)
        self.BioSaveCfgBtn.setGeometry(QtCore.QRect(20, 302, 104, 24))
        self.BioSaveCfgBtn.setObjectName("BioSaveCfgBtn")
        self.EcoProgressBar = QtWidgets.QProgressBar(self.groupBox_10)
        self.EcoProgressBar.setGeometry(QtCore.QRect(170, 302, 371, 25))
        self.EcoProgressBar.setProperty("value", 0)
        self.EcoProgressBar.setObjectName("EcoProgressBar")
        self.BioGetWeightBtn = QtWidgets.QPushButton(self.groupBox_10)
        self.BioGetWeightBtn.setEnabled(True)
        self.BioGetWeightBtn.setGeometry(QtCore.QRect(550, 300, 104, 24))
        self.BioGetWeightBtn.setObjectName("BioGetWeightBtn")
        self.groupBox_16 = QtWidgets.QGroupBox(self.EconomicsQTBox)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 370, 651, 71))
        self.groupBox_16.setObjectName("groupBox_16")
        self.lblOutputB = QtWidgets.QLabel(self.groupBox_16)
        self.lblOutputB.setGeometry(QtCore.QRect(10, 30, 631, 16))
        self.lblOutputB.setObjectName("lblOutputB")
        self.toolBox.addItem(self.EconomicsQTBox, "")
        self.SocialQTBox = QtWidgets.QWidget()
        self.SocialQTBox.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.SocialQTBox.setObjectName("SocialQTBox")
        self.line_12 = QtWidgets.QFrame(self.SocialQTBox)
        self.line_12.setGeometry(QtCore.QRect(10, 360, 660, 15))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.EcoLbl_2 = QtWidgets.QLabel(self.SocialQTBox)
        self.EcoLbl_2.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.EcoLbl_2.setObjectName("EcoLbl_2")
        self.MobMapNameLbl = QtWidgets.QLabel(self.SocialQTBox)
        self.MobMapNameLbl.setGeometry(QtCore.QRect(88, 0, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.MobMapNameLbl.setFont(font)
        self.MobMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.MobMapNameLbl.setObjectName("MobMapNameLbl")
        self.line_13 = QtWidgets.QFrame(self.SocialQTBox)
        self.line_13.setGeometry(QtCore.QRect(9, 10, 657, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.groupBox_9 = QtWidgets.QGroupBox(self.SocialQTBox)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 20, 651, 341))
        self.groupBox_9.setObjectName("groupBox_9")
        self.MobilityGetWeightBtn = QtWidgets.QPushButton(self.groupBox_9)
        self.MobilityGetWeightBtn.setEnabled(True)
        self.MobilityGetWeightBtn.setGeometry(QtCore.QRect(540, 290, 104, 24))
        self.MobilityGetWeightBtn.setObjectName("MobilityGetWeightBtn")
        self.MobilityWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_9)
        self.MobilityWeighTableWidget.setGeometry(QtCore.QRect(19, 30, 621, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MobilityWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.MobilityWeighTableWidget.setSizePolicy(sizePolicy)
        self.MobilityWeighTableWidget.setAcceptDrops(False)
        self.MobilityWeighTableWidget.setDragEnabled(True)
        self.MobilityWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.MobilityWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.MobilityWeighTableWidget.setRowCount(0)
        self.MobilityWeighTableWidget.setObjectName("MobilityWeighTableWidget")
        self.MobilityWeighTableWidget.setColumnCount(0)
        self.MobilityWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.MobilityWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.MobilityWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.MobilityWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.SocProgressBar = QtWidgets.QProgressBar(self.groupBox_9)
        self.SocProgressBar.setGeometry(QtCore.QRect(160, 290, 371, 25))
        self.SocProgressBar.setProperty("value", 0)
        self.SocProgressBar.setObjectName("SocProgressBar")
        self.MobSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_9)
        self.MobSaveCfgBtn.setGeometry(QtCore.QRect(10, 290, 104, 24))
        self.MobSaveCfgBtn.setObjectName("MobSaveCfgBtn")
        self.groupBox_17 = QtWidgets.QGroupBox(self.SocialQTBox)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 380, 651, 71))
        self.groupBox_17.setObjectName("groupBox_17")
        self.lblOutputC = QtWidgets.QLabel(self.groupBox_17)
        self.lblOutputC.setGeometry(QtCore.QRect(10, 30, 631, 16))
        self.lblOutputC.setObjectName("lblOutputC")
        self.toolBox.addItem(self.SocialQTBox, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.page_2.setObjectName("page_2")
        self.EnvLbl_2 = QtWidgets.QLabel(self.page_2)
        self.EnvLbl_2.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.EnvLbl_2.setObjectName("EnvLbl_2")
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setGeometry(QtCore.QRect(10, 10, 657, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_13.setGeometry(QtCore.QRect(11, 30, 661, 331))
        self.groupBox_13.setObjectName("groupBox_13")
        self.SocioGetWeightBtn = QtWidgets.QPushButton(self.groupBox_13)
        self.SocioGetWeightBtn.setGeometry(QtCore.QRect(550, 290, 104, 24))
        self.SocioGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.SocioGetWeightBtn.setObjectName("SocioGetWeightBtn")
        self.SocioWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_13)
        self.SocioWeighTableWidget.setGeometry(QtCore.QRect(20, 31, 630, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SocioWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.SocioWeighTableWidget.setSizePolicy(sizePolicy)
        self.SocioWeighTableWidget.setAcceptDrops(False)
        self.SocioWeighTableWidget.setDragEnabled(True)
        self.SocioWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.SocioWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.SocioWeighTableWidget.setRowCount(0)
        self.SocioWeighTableWidget.setObjectName("SocioWeighTableWidget")
        self.SocioWeighTableWidget.setColumnCount(0)
        self.SocioWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.SocioWeighTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.SocioWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.SocioWeighTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.SocioWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.SocioProgressBar = QtWidgets.QProgressBar(self.groupBox_13)
        self.SocioProgressBar.setGeometry(QtCore.QRect(170, 290, 371, 25))
        self.SocioProgressBar.setProperty("value", 0)
        self.SocioProgressBar.setObjectName("SocioProgressBar")
        self.SocioSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_13)
        self.SocioSaveCfgBtn.setGeometry(QtCore.QRect(20, 290, 104, 24))
        self.SocioSaveCfgBtn.setObjectName("SocioSaveCfgBtn")
        self.groupBox_18 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 370, 651, 71))
        self.groupBox_18.setObjectName("groupBox_18")
        self.lblOutputD = QtWidgets.QLabel(self.groupBox_18)
        self.lblOutputD.setGeometry(QtCore.QRect(10, 30, 631, 16))
        self.lblOutputD.setObjectName("lblOutputD")
        self.SocioMapNameLbl = QtWidgets.QLabel(self.page_2)
        self.SocioMapNameLbl.setGeometry(QtCore.QRect(70, 0, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.SocioMapNameLbl.setFont(font)
        self.SocioMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.SocioMapNameLbl.setObjectName("SocioMapNameLbl")
        self.toolBox.addItem(self.page_2, "")
        self.AnalysisQTBox = QtWidgets.QWidget()
        self.AnalysisQTBox.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.AnalysisQTBox.setObjectName("AnalysisQTBox")
        self.AnlsBtnBox = QtWidgets.QDialogButtonBox(self.AnalysisQTBox)
        self.AnlsBtnBox.setGeometry(QtCore.QRect(565, 504, 86, 23))
        self.AnlsBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.AnlsBtnBox.setObjectName("AnlsBtnBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 651, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.spinBoxClasNum = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBoxClasNum.setGeometry(QtCore.QRect(200, 30, 61, 22))
        self.spinBoxClasNum.setProperty("value", 5)
        self.spinBoxClasNum.setObjectName("spinBoxClasNum")
        self.RenderMapBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.RenderMapBtn.setGeometry(QtCore.QRect(520, 30, 111, 24))
        self.RenderMapBtn.setObjectName("RenderMapBtn")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 141, 20))
        self.label_7.setObjectName("label_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 100, 651, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.GraphBtn = QtWidgets.QPushButton(self.groupBox_7)
        self.GraphBtn.setGeometry(QtCore.QRect(520, 30, 111, 24))
        self.GraphBtn.setObjectName("GraphBtn")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(20, 35, 111, 20))
        self.label_3.setObjectName("label_3")
        self.LabelListFieldsCBox = QtWidgets.QComboBox(self.groupBox_7)
        self.LabelListFieldsCBox.setGeometry(QtCore.QRect(170, 33, 291, 22))
        self.LabelListFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelListFieldsCBox.setObjectName("LabelListFieldsCBox")
        self.groupBox_8 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 190, 651, 191))
        self.groupBox_8.setObjectName("groupBox_8")
        self.BuiltSlider = QtWidgets.QSlider(self.groupBox_8)
        self.BuiltSlider.setEnabled(True)
        self.BuiltSlider.setGeometry(QtCore.QRect(200, 10, 321, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BuiltSlider.sizePolicy().hasHeightForWidth())
        self.BuiltSlider.setSizePolicy(sizePolicy)
        self.BuiltSlider.setProperty("value", 25)
        self.BuiltSlider.setSliderPosition(25)
        self.BuiltSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BuiltSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.BuiltSlider.setTickInterval(25)
        self.BuiltSlider.setObjectName("BuiltSlider")
        self.BioSlider = QtWidgets.QSlider(self.groupBox_8)
        self.BioSlider.setEnabled(True)
        self.BioSlider.setGeometry(QtCore.QRect(200, 51, 321, 51))
        self.BioSlider.setProperty("value", 25)
        self.BioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BioSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.BioSlider.setTickInterval(25)
        self.BioSlider.setObjectName("BioSlider")
        self.MobSlider = QtWidgets.QSlider(self.groupBox_8)
        self.MobSlider.setEnabled(True)
        self.MobSlider.setGeometry(QtCore.QRect(200, 90, 321, 51))
        self.MobSlider.setProperty("value", 25)
        self.MobSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MobSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.MobSlider.setTickInterval(25)
        self.MobSlider.setObjectName("MobSlider")
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setGeometry(QtCore.QRect(20, 30, 161, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 161, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 161, 21))
        self.label_4.setObjectName("label_4")
        self.pushBtnEval = QtWidgets.QPushButton(self.groupBox_8)
        self.pushBtnEval.setEnabled(True)
        self.pushBtnEval.setGeometry(QtCore.QRect(550, 50, 81, 91))
        self.pushBtnEval.setObjectName("pushBtnEval")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 161, 21))
        self.label_5.setObjectName("label_5")
        self.SocioSlider = QtWidgets.QSlider(self.groupBox_8)
        self.SocioSlider.setEnabled(True)
        self.SocioSlider.setGeometry(QtCore.QRect(200, 130, 321, 51))
        self.SocioSlider.setProperty("value", 25)
        self.SocioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SocioSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.SocioSlider.setTickInterval(25)
        self.SocioSlider.setObjectName("SocioSlider")
        self.toolBox.addItem(self.AnalysisQTBox, "")
        self.RulesQTBox = QtWidgets.QWidget()
        self.RulesQTBox.setGeometry(QtCore.QRect(0, 0, 670, 466))
        self.RulesQTBox.setObjectName("RulesQTBox")
        self.CritExtractBtn = QtWidgets.QPushButton(self.RulesQTBox)
        self.CritExtractBtn.setGeometry(QtCore.QRect(520, 10, 141, 31))
        self.CritExtractBtn.setObjectName("CritExtractBtn")
        self.RulesListWidget = QtWidgets.QListWidget(self.RulesQTBox)
        self.RulesListWidget.setGeometry(QtCore.QRect(10, 60, 651, 291))
        self.RulesListWidget.setObjectName("RulesListWidget")
        self.SaveRulesBtn = QtWidgets.QPushButton(self.RulesQTBox)
        self.SaveRulesBtn.setGeometry(QtCore.QRect(580, 360, 81, 31))
        self.SaveRulesBtn.setObjectName("SaveRulesBtn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.RulesQTBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 651, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.baseLbl = QtWidgets.QLabel(self.groupBox_3)
        self.baseLbl.setGeometry(QtCore.QRect(20, 20, 621, 21))
        self.baseLbl.setObjectName("baseLbl")
        self.toolBox.addItem(self.RulesQTBox, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(5)
        self.toolBox.layout().setSpacing(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.OutlEdt, self.RetriveFileTBtn)
        Dialog.setTabOrder(self.RetriveFileTBtn, self.SetBtnBox)
        Dialog.setTabOrder(self.SetBtnBox, self.SetBtnHelp)
        Dialog.setTabOrder(self.SetBtnHelp, self.SetBtnAbout)
        Dialog.setTabOrder(self.SetBtnAbout, self.AnlsBtnBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MESUE - Modelo de Evaluación de Sustentabilidad Urbana Espacial"))
        self.SetBtnHelp.setText(_translate("Dialog", "Ayuda"))
        self.SetBtnAbout.setText(_translate("Dialog", "Acerca de"))
        self.BaseLayerLbl.setText(_translate("Dialog", "TextLabel"))
        self.RetriveFileTBtn.setText(_translate("Dialog", "..."))
        self.groupBox.setTitle(_translate("Dialog", "A Ambiente Construido"))
        self.addLayerBtnBUILT.setText(_translate("Dialog", ">>>"))
        self.removeLayerBtnBUILT.setText(_translate("Dialog", "<<<"))
        self.groupBox_2.setTitle(_translate("Dialog", "B Ambiente Biofísico"))
        self.removeLayerBtnBIO.setText(_translate("Dialog", "<<<"))
        self.addLayerBtnBIO.setText(_translate("Dialog", ">>>"))
        self.groupBox_4.setTitle(_translate("Dialog", "C Movilidad Urbana"))
        self.addLayerBtnMOB.setText(_translate("Dialog", ">>>"))
        self.removeLayerBtnMOB.setText(_translate("Dialog", "<<<"))
        self.EcoFieldsLbl_2.setText(_translate("Dialog", "Indicadores:"))
        self.EcoFieldsLbl_3.setText(_translate("Dialog", "Salida:"))
        self.groupBox_12.setTitle(_translate("Dialog", "D Dinámicas Socio-espaciales"))
        self.addLayerBtnSocialSpatial.setText(_translate("Dialog", ">>>"))
        self.removeLayerBtnSocialSpatial.setText(_translate("Dialog", "<<<"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Análisis"))
        self.EnvLbl.setText(_translate("Dialog", "Layer     "))
        self.groupBox_11.setTitle(_translate("Dialog", "Normalización y pesos"))
        self.BuiltGetWeightBtn.setText(_translate("Dialog", "Aplicar"))
        self.BuiltSaveCfgBtn.setText(_translate("Dialog", "Guardar"))
        self.groupBox_15.setTitle(_translate("Dialog", "Output >_"))
        self.lblOutputA.setText(_translate("Dialog", "mesue:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EnvironmentaleQTbox), _translate("Dialog", "A Ambiente Construido"))
        self.EcoLbl.setText(_translate("Dialog", "Layer     "))
        self.groupBox_10.setTitle(_translate("Dialog", "Normalización y pesos"))
        self.BioSaveCfgBtn.setText(_translate("Dialog", "Guardar"))
        self.BioGetWeightBtn.setText(_translate("Dialog", "Aplicar"))
        self.groupBox_16.setTitle(_translate("Dialog", "Output >_"))
        self.lblOutputB.setText(_translate("Dialog", "mesue:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EconomicsQTBox), _translate("Dialog", "B Ambiente Biofísico"))
        self.EcoLbl_2.setText(_translate("Dialog", "Layer     "))
        self.groupBox_9.setTitle(_translate("Dialog", "Normalización y pesos"))
        self.MobilityGetWeightBtn.setText(_translate("Dialog", "Aplicar"))
        self.MobSaveCfgBtn.setText(_translate("Dialog", "Guardar"))
        self.groupBox_17.setTitle(_translate("Dialog", "Output >_"))
        self.lblOutputC.setText(_translate("Dialog", "mesue: "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.SocialQTBox), _translate("Dialog", "C Movilidad Urbana"))
        self.EnvLbl_2.setText(_translate("Dialog", "Layer     "))
        self.groupBox_13.setTitle(_translate("Dialog", "Normalización y pesos"))
        self.SocioGetWeightBtn.setText(_translate("Dialog", "Aplicar"))
        self.SocioSaveCfgBtn.setText(_translate("Dialog", "Guardar"))
        self.groupBox_18.setTitle(_translate("Dialog", "Output >_"))
        self.lblOutputD.setText(_translate("Dialog", "mesue:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "D Dinámicas Socio-espaciales"))
        self.groupBox_5.setTitle(_translate("Dialog", "Mapas de sustentabilidad"))
        self.RenderMapBtn.setText(_translate("Dialog", "Cargar mapas"))
        self.label_7.setText(_translate("Dialog", "Número de clases en mapas"))
        self.groupBox_7.setTitle(_translate("Dialog", "Sustainability charts"))
        self.GraphBtn.setText(_translate("Dialog", "Build charts"))
        self.label_3.setText(_translate("Dialog", "Select name field"))
        self.groupBox_8.setTitle(_translate("Dialog", "Sustentabilidad general"))
        self.label.setText(_translate("Dialog", "A Ambiente Construido"))
        self.label_2.setText(_translate("Dialog", "B Ambiente Biofísico"))
        self.label_4.setText(_translate("Dialog", "C Movilidad Urbana"))
        self.pushBtnEval.setText(_translate("Dialog", "Evaluar"))
        self.label_5.setText(_translate("Dialog", "C Dinámicas Socio-espaciales"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisQTBox), _translate("Dialog", "Análisis"))
        self.CritExtractBtn.setText(_translate("Dialog", " Extract rules"))
        self.SaveRulesBtn.setText(_translate("Dialog", "Save rules"))
        self.groupBox_3.setTitle(_translate("Dialog", "Active layer"))
        self.baseLbl.setText(_translate("Dialog", "TextLabel"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.RulesQTBox), _translate("Dialog", "Rules"))

